### ISSUE TITLE
Fixed Input in Etcher

### ISSUE THREAD

**Issue by brachy84** [phantamanta44/Lazy-AE2#4] opened 2019-07-09 03:51 UTC
Make all the inputs changable with crafttweaker so we can actually change recipes.

**Comment by phantamanta44** [comment] 2019-07-09 20:33
okay so i came across an issue: by design, the top and bottom slots of the etcher only accept redstone and silicon; this makes life easier for everyone because it means you can pipe stuff into the machine in any order and it'll go into the proper slot. of course, this won't work at all if the inputs are unfixed because there won't be any distinction between the three ingredient types. do you have any suggestions for resolving this?

**Comment by brachy84** [comment] 2019-07-10 15:02
Maybe you can make the crafttweaker script line must contain three input items: first is top, second is mid and third is bottom. I don't know muchabout modding so I don't know if this is possible

**Comment by phantamanta44** [comment] 2019-07-10 20:22
let me try to make a more illustrative example: suppose i try to push an item into an etcher using a pipe. the item handling logic is as follows:
```
if the item is redstone:
  put the item in the top slot
otherwise, if the item is silicon:
  put the item in the bottom slot
otherwise:
  put the item in the middle slot
```
this logic is in place so users don't have to worry about items going into the wrong slots when they pipe them into an etcher. if recipes can have any arbitrary ingredients in the top and bottom slots, however, this will no longer work. i need a resolution to this, and i can't really think of a good one

**Comment by brachy84** [comment] 2019-07-11 15:01
You could make a config where you can define top and bottom slot

**Comment by MrTK-Dev** [comment] 2019-07-21 09:20
You could add a list which contains the Inputs for the fitting slot. But _then_ you may not use the same item in different input-slots.
e.g.:
```
recipe 1, 2, 3,...
[stone, wood, redstone]
[plank, diamond, coal]
[cobalt, ardite, lapis]
```
The machine could check if the **item** is in **one** of those lists (they have to get filled from additional _crafttweaker_ recipes)
Maybe this helps : )

**Closed as completed** 2020-07-23 04:31 UTC
