### ISSUE TITLE
I have to use @threng to see what is in my ME system.

### ISSUE THREAD

**Issue by jk1895** [phantamanta44/Lazy-AE2#46] opened 2021-01-09 21:37 UTC
Hi,
@lazy is not showing anything related to your mod. I have to write @throng (whatever this means).

![2021-01-09_22 35 23](https://user-images.githubusercontent.com/20401451/104109152-45ee0e80-52cb-11eb-8b0c-f94b0a7162c8.png)
![2021-01-09_22 35 29](https://user-images.githubusercontent.com/20401451/104109154-4686a500-52cb-11eb-9e6d-13f1bcce9368.png)

**Comment by phantamanta44** [comment] 2021-01-10 02:33
`threng` is lazy ae2's mod id. this is expected behaviour, since the search mechanism uses mod ids rather than mod names, and it can't be fixed without either a change on the ae2/jei side or a change of mod id, which is no good

**Comment by jk1895** [comment] 2021-01-10 08:03
And why is it not good? It should be absolutely no problem to change the mod ID. Find "threng" raplace all with lazyae2 or lazy_ae2. Compile it again. Done.

**Comment by phantamanta44** [comment] 2021-01-10 08:57
well, for starters, every id used in an old world would become unmapped if they updated lazy ae2...

**Comment by jk1895** [comment] 2021-01-10 09:05
Yes, there's something to that. But this wouldn't be the first time something like this has happened. You could put a big fat warning in red: "Only update when you start a new world!" :D
But anyway, you need to know that, whether it's good the way it is. I was annoyed by it. Otherwise it's a great mod! Thank you.

**Closed as completed** 2021-11-27 22:55 UTC
