### ISSUE TITLE
Mass Assembler Controller drop

### ISSUE THREAD

**Issue by EnterFor** [phantamanta44/Lazy-AE2#25] opened 2020-03-06 08:32 UTC
I submitted this question before
https://github.com/phantamanta44/Lazy-AE2/issues/17

This will happen again when the server is restarted

Mod：1.1.12
Forge：2847

**Comment by phantamanta44** [comment] 2020-03-15 03:08
unable to replicate. can you give more details?

**Comment by EnterFor** [comment] 2020-03-18 03:47
I don't know what else to offer...
The main part is restarting the server
And the player has a security terminal

**Comment by EnterFor** [comment] 2020-03-18 03:49
Is it related to the server type?
What I use is: https://github.com/Luohuayu/CatServer

**Comment by phantamanta44** [comment] 2020-03-19 03:35
probably; i'm unable to replicate at all on a vanilla server. my opinion is that it's on the catserver developers to fix this problem, since my mod nominally targets only the vanilla server platform and it's catserver's responsibility to emulate the vanilla server.

**Comment by idnthvn** [comment] 2020-03-20 22:42
EnterFor, It be helpfull if you would post more information
Minecraft Version:
Forge Version:
SpongeForge? If so, what version:
Hybrid Server? Example: CatServer. If so, What Version:
AE2 Version:
Lazy AE2 Version:
Maybe even a log. Because Phantamanta44 is assuming you updated to the latest version on everything. Maybe you did not update and he is chasing a problem because you did not update their mod. Reason why i asked for a log. This info should just be standard. 
CatServer saying its AE2,   Yet I have no issue on my server with version 12 of LazyAE2 with Security Terminals and everything. (other than my EnderIO Conduits, but that should be fixed i think now :P

**Comment by phantamanta44** [comment] 2020-05-06 16:52
I think I may have identified a very rare edge case where this can happen, which would explain why I've been having a hard time replicating the issue. I'll investigate.

**Comment by phantamanta44** [comment] 2020-05-07 04:15
give [the latest release](https://www.curseforge.com/minecraft/mc-mods/lazy-ae2/files/2950352) a shot; i'll close this issue once it's confirmed that the bug is fixed

**Comment by phantamanta44** [comment] 2020-05-13 20:21
will assume it's fixed

**Closed as completed by phantamanta44** 2020-05-13 20:21 UTC
